### ISSUE TITLE
Steering controller testing

### ISSUE THREAD

**Issue by AbBaSaMo** [Monash-Connected-Autonomous-Vehicle/ESDA#57]
### Overview
We have a ROS2 node called `parallelogram_steerign_controller` which listens to a topic called `cmd_vel` which outputs Twist messages and then calculates the position the ESDA servo must turn to in order for the vehicle to turn appropriately. 

As part of this issue, we need to send a variety of `cmd_vel` messages while running the steering controller while observing how well the system runs and modifying the 

### Relevant resources
- (parallelogram_steering_controller node)[https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/blob/sensor-integration/esda_control/esda_control/parallelogram_steering_controller.py]
- (Twist message)[https://docs.ros.org/en/noetic/api/geometry_msgs/html/msg/Twist.html]
- (Dynamixel servo setup)[https://www.youtube.com/watch?v=E8XPqDjof4U&list=PLRG6WP3c31_Xg_IPNGJybiP8H4Lpy2RuY&index=1]

### Acceptance criteria
- [ ] The controller just needs to be able to cause the servo to spin to an appropriate position in response to given `cmd_vel` values as verifies by software and mechanical members

### Todo
- [ ] Organise a time with mechanical members
- [ ] Put the ESDA on the ground
- [ ] Connect and turn on the servo
- [ ] Run the `parallelogram_steering_controller`
- [ ] In a separate terminal, send twist messages to the topic `cmd_vel`
- [ ] Observe how the servo and wheels turn and ensure mechanical and software agree it's turnign appropriately
