### ISSUE TITLE
Control integration testing

### ISSUE THREAD

**Issue by AbBaSaMo** [Monash-Connected-Autonomous-Vehicle/ESDA#59]
### Overview
Control systems are defined by software as the following aspects of the stack: the component that facilitates drive wheels spinning i.e. `ros2_control` including the `MCU_interface` hardware component. Almost all of this will be abstracted in the sense that electrical will handle its implementation and software will only have had to configure the launch files for `ros2_control`. 

The rest of control is also abstracted in the sense that software's stack does not touch or care about it including: the safety light, hand held controller, autonomous mode flags.

This task requires all such control components handled by software AND electrical to be running at once and for all acceptance criteria for tasks related to the components to have passed while they are all running.

**DO NOT CONDUCT CONTROL INTEGRATION TESTING WHILE E-STOP AND MECHANICAL STOP ARE NOT WORKING**

### Relevant resources
Refer to the following issues
- https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/issues/65

### Acceptance criteria
Acceptance criteria is the fulfilment of all criteria as defined for the below issues but while everything is running
- https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/issues/65

### Todo
- [ ] Determine a time with electrical and mechanical to conduct this testing
- [ ] Develop a plan on where and how the vehicle will be tested to ensure safety
- [ ] Send `cmd_vel` messages and verify that the vehicle fulfils all acceptance criteria
