### ISSUE TITLE
Fine tuning sensor positioning

### ISSUE THREAD

**Issue by AbBaSaMo** [Monash-Connected-Autonomous-Vehicle/ESDA#63]
### Overview
3 components of our sensors must be positioned optimally: the VLP16 puck, the piksi antenna (NOT the chip) and the Zed2i camera. This is to ensure sensing is accurate and adequate. In theory, only the piksi antenna needs palying around with but observations and modifications to all are fine so as long as they are immediately communicated with mechanical so they can update their CAD/build and so as long as the urdf is updated.

If it is found that sensors interfere with each other e.g. the lidar detects the piksi antenna as an obstacle, then a new issue will need to be created to filter such interference out or deal with it appropriately.

### Relevant resources
- [Swift piksi antenna placement guide](https://support.swiftnav.com/support/solutions/articles/44001904315-gnss-antenna-placement-guidelines)

### Acceptance criteria
- [ ] Sensors must be able to all detect data without interference form each other or other parts of the vehicle in an outside setting

### Todo
- [ ] Wheel the esda out onto a grassy area
- [ ] Spray paint some lines and place some obstacles
- [ ] While the sensor software blocks are running, observe outputs on rviz and move the piksi antenna to an appropriate position
- [ ] If the zed cam needs adjusting, adjust the tilt
- [ ] Note any changes needed to URDF where changes in zed cam or VLP16 puck positioning are the only things relevant
