### ISSUE TITLE
Implement PID controller

### ISSUE THREAD

**Issue by AbBaSaMo** [Monash-Connected-Autonomous-Vehicle/ESDA#64]
### Overview
Originally electrical handled PID control on the MCU chip but now that is being delegated to us. It would reduce the amount of overhead their chips will use. PID from what I understand provides some sort of homeostasis between desired wheel velocity and actual wheel velocity.

Some existing implementations exist but they need to fulfil our interfaces i.e. take in the command velocity, wheel velocity as measured by encoders and then output wheel acceleration. This needs to be done per wheel so PID control for wheel 1 will be done separately to wheel 2.

<img src="https://github.com/user-attachments/assets/f9108f80-9fc5-4653-81ad-692d3ba6ced4" width="400"/>

### Relevant resources
- [PID controller from ROS2_control](https://control.ros.org/master/doc/ros2_controllers/pid_controller/doc/userdoc.html)
- [Control toolbox package](https://github.com/ros-controls/control_toolbox/)
- [ros2 pid library](https://github.com/dottantgal/ros2_pid_library)

### Acceptance criteria
- [ ] accepts cmd vel and wheel velocity as inputs
- [ ] outputs wheel acceleration values
- [ ] wheels spin appropriately when run with the MCU interface node

### Todo
- [ ] research potential packages we could use 
- [ ] if no packages found, implement a ros node in the control package for PID
- [ ] the node needs to take in cmd vel twist messages
- [ ] the node then uses appropriate PID algorithms (idk what it's called) to determine the desired acceleration of the 2 drive wheels independently
- [ ] the node then sends this to the MCU chip
- [ ] the MCU chip sends back the velocity of each wheel
- [ ] the PID node uses this and the cmd vel values to continuously generate appropriate acceleration values
- [ ]
