### ISSUE TITLE
Find compute unit alternative

### ISSUE THREAD

**Issue by AbBaSaMo** [Monash-Connected-Autonomous-Vehicle/ESDA#69]
### Overview
The hive is good, but the hive is heavy.. and so the electrical and mechanical team require that we find a more lightweight compute unit for running our software on. A few alternatives exist, each with their own pros and cons and preferences from leads so this task aims to get the highest preference working otherwise the next best and so on.

As for the alternatives, refer to the following table

<table>
<tbody>
<tr>
<th>Pref </th><th>Alternative </th><th>Pros</th><th>Cons</th>
</tr>

<tr>
<td>1</td><td>MCAV owned Alienware with ubuntu 22.04 install and ROS2 humble</td>
<td>
No need to spend money
</td>
<td>
<ul>
<li>One of them is in use by UA and breaks when we install zed-ros2-wrapper dependencies</li>
<li>The other one needs upgrading from Ubuntu 18.04 to 22.04 (not a biggie) but might also have other issues iirc</li>
</ul>
</td>
</tr>

<tr>
<td>2</td><td>Buying a Jetson Orin Nano (not nano, ORIN nano)</td>
<td>
Fulfils our needs
</td>
<td>
costs 1.1k AUD (not too much but still a good chunk of our budget)
</td>
</tr>

<tr>
<td>3</td><td>Using our good old (old) Jetson TX2</td>
<td>
Already in workshop 2 and we have 2 of them
</td>
<td>
<ul>
<li>Requires extra effort to get ROS2 humble working on it as it can only install up to ubuntu 20.04</li>
<li>Since it's old (and from experience) we might encounter general issues working with it</li>
</ul>
</td>
</tr>
</tbody>
</table>

### Relevant resources
- [Installing 20.04 on a Jetson TX2](https://qengineering.eu/install-ubuntu-20.04-on-jetson-nano.html) <img src="https://github.com/user-attachments/assets/2cb5a8b7-7e26-4c22-8400-f254a11f225e" width="300"/>
- [Upgrade ubuntu 18.04 to 22.04](https://askubuntu.com/questions/1454762/18-04-22-04-upgrade)
- [ROS2 humble installation guide](https://docs.ros.org/en/humble/Installation.html)
- [ESDA repo README.md](https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA)

### Acceptance criteria
- [x] Ros2 humble working on any of the 3 listed devices from highest to lowest preference

### Todo 
- [x] Install ubuntu 22.04 on the 18.04 alienware
- [x] Install all deps and ensure the ESDA repo can be run [note the alienware needs a CUDA enabled NVIDIA GPU]
- [ ] If this doesn't work, Saami and I have found the Jetson Orin Nano (again note, Orin nano is different from the nano) should be suitable but double check and do some research including looking into system requirements for drivers and dependencies we use on top of requirements for ROS2 humble
- [ ] Negotiate purchase of Jetson Orin nano
- [ ] Setup and install deps on Orin nano
- [ ] If you have gotten to this stage and neither the Alienware nor the Orin nano work, then begin your attempt at configuring the Jetson TX2s (we have 2 in WS2, do both so there are 2 copies to work with)

**Comment by Rikidink** [comment]
Following this [forum post](https://askubuntu.com/questions/1454762/18-04-22-04-upgrade) to upgrade from Ubuntu 18.04 -> 22.04:
At the
sudo do-release-upgrade
Got "Could not calculate the upgrade" error seemingly because of incompatible/broken packages between 18.04 and 20.04.
Error in /var/log/dist-upgrade/main.log :
453 ERROR Dist-upgrade failed: 'E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.'
Resolved by [removing python-dev](https://askubuntu.com/questions/1279062/upgrade-from-18-04-to-20-04-prevented-by-eerror-pkgproblemresolverresolve-g):
sudo apt remove python-dev
sudo apt autoremove

**Comment by Rikidink** [comment]
Finished update to 22.04.
Installing ESDA repo (and dependencies) but installing nvidia and cuda drivers as per ESDA repo readme breaks Ubuntu:
```
# install driver
sudo apt-get install -y nvidia-driver-550-open
sudo apt-get install -y cuda-drivers-550
```
Entered recovery mode and deleted drivers to get it in a bootable state again:
```
sudo apt-get purge nvidia*
```

**Comment by AbBaSaMo** [comment]
@Rikidink this is the same issue we encountered with the other Alienware we have that is currently used for the Streetdrone project.

See if any of the suggested fixes below work:
- https://askubuntu.com/questions/955589/ubuntu-will-not-boot-normally-after-nvidia-driver-install
- https://askubuntu.com/questions/1129516/black-screen-at-boot-after-nvidia-driver-installation-on-ubuntu-18-04-2-lts
- https://forums.developer.nvidia.com/t/i-cannot-boot-ubuntu-22-04-after-installing-latest-nvidia-driver/251267/13

As a summary, some suggest using an older version of the driver, others suggest deleting certain files that somehow fix the issue. Once these and any other issues have been exhausted and we know it definitely won't work, let me know and we can close the issue until we get our hands on the orin nano.

**Comment by Rikidink** [comment]
The Alienware can now run the stack (NOTE: used the sensor-integration branch of the ESDA repo). Closing issue temporarily until getting the Orin Nano to test on as well.
