### ISSUE TITLE
Demo night sim

### ISSUE THREAD

**Issue by AbBaSaMo** [Monash-Connected-Autonomous-Vehicle/ESDA#70]
### Overview
Demo night is in week 8. We want a hardware in the loop demo. This will involve:
- Running the simulation with Nav2 integrated
- Putting the ESDA on a stand
- Connecting it to the control syste,s
- Getting the drive wheels to mirror what the sim is doing

### Relevant resources
- Nav2 docs
- URDF docs

### Acceptance criteria
- [ ] URDF needs to have front steer wheels replaced with a frictionless caster
- [ ] Migrate to diff drive controller [can use gazebo plugin or ros2 control works case]
- [ ] Have a map of the IGVC course to spawn the robot inside
- [ ] Have Nav2 drive the robot to a user defined waypoint while basic lidar based obstacle detection and avoidance

### Todo
- [ ] Update URDF
- [ ] Include GNSS in URDF
- [x] Ask anthony where the map is
- [ ] Find the map in the part of the repo anthony pointed to: open each file in gazebo to see which on it is
- [ ] Integrate with Nav2 using appropriate dependency management and launching
- [ ] Test it and test it with Samuel Tri

**Comment by AbBaSaMo** [comment]
I've updated the urdf to utilise casters as frictionless spheres. Included gazebo diff drive controller once again and added plugins to simulate IMU/GNSS in piksi.xacro obtained from https://medium.com/@bytesrobotics/a-review-of-the-ros2-urdf-gazebo-sensor-91e947c633d7.

Yet to test it but the only thing to really test is the IMU/GNSS component.

**Comment by Jiawei-Liao** [comment]
I think the correct map/world is lino_track.yaml under /maps and world_only.model under /worlds. (I think world_only.model is the default world setting since it's used for tb3 sim)

![Image](https://github.com/user-attachments/assets/7e226a6a-6f36-4d73-9110-49d04a4cdaf6)

The Gazebo doesn't show anything...

![Image](https://github.com/user-attachments/assets/5ede9ec9-110d-45e1-b9a0-fc17a05b7372)

When I tried to change world_only.model to lino_map.world, it give me this repeatedly until it crashed.

![Image](https://github.com/user-attachments/assets/cdd4b192-307e-4041-8ea3-37f0db77da0e)

Doesn't seem like an error? This is the final messages it printed before crashing/closing.

![Image](https://github.com/user-attachments/assets/beb1d3d1-c131-458a-829b-40e1c889630e)

I think using world_only.model is fine? ChatGPT says it's for environment (lighting, physics). Gazebo didn't show anything so I can't verify this.

Not sure if it's my PC but I can't get the robot to spawn. I'm using default tb3 and I also tried with a fresh clone of the repo. All of them can load up the map but can't spawn the robot. Does it work for someone else?

**Comment by AbBaSaMo** [comment]
@Jiawei-Liao when you do figure it out, rename the world to igvc and then whatever the extension is.

If we can't figure it out over time, we can always ask anthony

**Comment by AbBaSaMo** [comment]
For my own sub-tasks, I have the following to do:

- [ ] Test diff drive with ''casters''
- [ ] Test piksi and imu pluging
- [ ] Integrate with slam toolbox and robot localisation

After this it can be integrated with nav2

**Comment by AbBaSaMo** [comment]
idk if this fixed gazebo diff drive plugin or increasing the twist speed but it now works `sudo apt install ros-humble-gazebo-ros-pkgs`

**Comment by AbBaSaMo** [comment]
@Monash-Connected-Autonomous-Vehicle/esda-team 

Quite janky when it moves. The "caster" wheels in the front have no friction so it shouuld be fine but it jumps around as shown in the video below.

Any ideas how to fix? I'll play around with inertia but all I can really do is update the mass until I find a sweet spot. Maybe position a single wheel at centre instead of 2.

https://github.com/user-attachments/assets/6e19b546-7d4b-4465-b5dd-2dc023d7f3a2

**Comment by AbBaSaMo** [comment]
Moved casters forward a bit and it removed the lurching. Also added a rear caster, not sure if needed, can test without and the mass is not 0 but close to it

![Image](https://github.com/user-attachments/assets/9f754585-84dd-4d08-bed0-724a18e5d5e3)

**Comment by dylan-gonzalez** [comment]
The caster wheels aren't spinning, so changing the position of them won't fix anything.

Where have you set the friction to zero? I've done something like [this](https://github.com/Monash-Connected-Autonomous-Vehicle/adr/blob/d52f4efa8dcf971ba369b3bb36d7c0033ab95c13/adr_description/urdf/adr/adr.gazebo#L117-L135) for mine, I don't see anything like that in your urdf. (mine is for Gazebo Fortress so I'm not sure if the syntax is the same for classic but it probably is)

**Comment by AbBaSaMo** [comment]
Oh, interesting. I used the same technique as josh newans in line 164 here where he basically set the mass to a very low number
https://github.com/joshnewans/articubot_one/blob/main/description/robot_core.xacro

The intertial_cylinder element in another file is where intertial physics is defined. In our repo it is under esda_sim/description/util

Problem was that without moving the casters forward, it jumps forward when the vehicle stops so I had to '''balance''' it if that makes sense. Will try out your solution when I'm next in.

Did you basically re-create the urdf in gazebo using sdf syntax??

**Comment by dylan-gonzalez** [comment]
> Did you basically re-create the urdf in gazebo using sdf syntax??

The only SDF I have is the world file. Everything else is URDF - I use `<gazebo>` tags.

**Comment by Jiawei-Liao** [comment]
I got the sim to run on the test world with tb3 bot. Small bot in such a big map. Movement works.

![Image](https://github.com/user-attachments/assets/9ee2cdbd-3c9f-45c3-9961-3a490c80db44)
![Image](https://github.com/user-attachments/assets/d192ef4c-fcab-4b47-90fe-0bb3c5241928)

There is some output to /cmd_vel topic. Looks right I think? but not sure why only 1 value from linear/angular is being used at a time

![Image](https://github.com/user-attachments/assets/ff73916d-307e-45c7-8fe7-f526864165c0)

Something that I noticed is that RVIZ laggs sometimes, resulting in the bot teleporting. But gazebo is smooth so I think it should be fine?

This is what I did to fix the issues I had before.
install:
`sudo apt install ros-humble-rmw-cyclonedds-cpp`

add to .bashrc:
`export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`

go to:
/opt/ros/humble/share/turtlebot3_navigation2/param

edit waffle.yaml (with sudo):
change: `robot_model_type: "differential"`
to: `robot_model_type: "nav2_amcl::DifferentialMotionModel`

then restart

This is the command used to run the sim:
`ros2 launch nav2_bringup esda_simulation_launch.py`

To change the map, change the maps and worlds variables
It is currently using nav2_params instead of esda_params. I don't think we need to change this for the demo since I don't think we need anything else (custom layers/plugin)
The model is waffle but it can be changed with robot_name and robot_sdf variables.

**Comment by dylan-gonzalez** [comment]
> but not sure why only 1 value from linear/angular is being used at a time

what do you mean? linear x is forward, angular z is yaw. Can your bot move sideways, or fly in the air? Otherwise these values make sense

> Something that I noticed is that RVIZ laggs sometimes

Can you be specific? Do you mean one of the transforms is lagging/glitching?

**Comment by Jiawei-Liao** [comment]
> what do you mean? linear x is forward, angular z is yaw. Can your bot move sideways, or fly in the air? Otherwise these values make sense
Ah I see, that makes sense. I thought it would use a combination of linear x, y, z. But I guess the bot is just moving in it's x direction, not the RVIZ axis.

> Can you be specific? Do you mean one of the transforms is lagging/glitching?

https://github.com/user-attachments/assets/2c000e79-6d0b-49fa-bfe2-db73ecbde900

**Comment by dylan-gonzalez** [comment]
Yeah so that's something to do with your localisation. You're running AMCL right? So maybe look at some forums related to that, probs have to tune parameters or something.

But everything is working fine it seems in terms of gazebo and rviz

**Comment by AbBaSaMo** [comment]
@Jiawei-Liao did i miss something or is there a reason the test world does not have the ground with the grass and lanes?

**Comment by Jiawei-Liao** [comment]
> [@Jiawei-Liao](https://github.com/Jiawei-Liao) did i miss something or is there a reason the test world does not have the ground with the grass and lanes?

oh is that not the map? The other worlds/maps are all the same as this. I'll ask anthony on this. Is he still on slack?

**Comment by AbBaSaMo** [comment]
It's the right map but it doesn't seem to have loaded properly. Idk if u remember but when Anthony was showcasing it, it had a grass plane with a track.

He's on slack but idk if he's in the team so might be best to shoot him an email.

**Comment by AbBaSaMo** [comment]
- [ ] add nav2 to package.xml in launch pkg
- [ ] copy over the 2 map files and any configs to esda_sim
- [ ] create the launch file while pointing to relevant urdfs/,ap files and configs

**Comment by Jokua** [comment]
Just writing a guide on how to get the simulator to run with the basic stuff from the Nav2 Tutorial after Jiawei's fixes:

`source /opt/ros/humble/setup.bash`
`export TURTLEBOT3_MODEL=waffle`
`export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models`
`export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`
`ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False`

After it launches gazebo and rviz2, you have to set the 2D pose estimate of the robot. You can do that by guess-timating the spot by looking at the gazebo sim.

In order to set the goal pose, don't forget to click, hold and aim it in the direction you want it to face at the goal. You can click the goal but it's better if you set the goal pose facing where you want it to to show that it can compensate for that or something

**Comment by AbBaSaMo** [comment]
Need the following links in the URDF
- [x] base_link
- [x] base_footprint

Regarding the odom -> base_link tf, using robot_localisation
- [x] output GPS from gps plugin as /navsatfix
- [x] output imu as /imu
- [x] output wheel odom from gazebo diff drive plugin as /wheel_odom
- [x] configure robot_localization and verify the transforms

**Comment by AbBaSaMo** [comment]
Now slam tool box is working witht he URDF. I changed the ROS DOMAIN ID to 10 as i was getting transforms not defined in my urdf, and it seemed after some time the map was empty but then began publishing fine

![image](https://github.com/user-attachments/assets/52541273-072c-4ad4-88a5-6f2a363273b8)

Now on to the last step: Nav2 integration :D
